### ISSUE TITLE
应该加一个是否包含源码的功能，一次性可以吧java文件和class文件同时导出

### ISSUE THREAD

**Issue by adgar-shi** [Liang-Dongxing/patcher#4]
补丁给到项目上一般都会带上java文件，方便后续在打补丁有冲突的时候可以直接下载服务器上的java文件来合并代码

**Comment by Liang-Dongxing** [comment]
![image](https://user-images.githubusercontent.com/19583575/230444822-65303506-90a1-459c-a805-24a0323f2904.png)
这个功能能就是导出源码文件的。
